/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsa;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mustafa
 */
public class StrangerGui extends javax.swing.JFrame {

    static ServerSocket server;
    static Socket client;
    static DataInputStream in;
    static DataOutputStream out;
    static String msg;
    static ArrayList<Integer> encArrayList = new ArrayList<Integer>();
    static RSA_PublicKey publicKey = new RSA_PublicKey();
    static Stranger stranger1;

    static class Reading extends Thread {

        ObjectInputStream objectInput;

        Reading() {

        }

        @Override
        public void run() {
            super.run(); //To change body of generated methods, choose Tools | Templates.

            try {
                server = new ServerSocket(7070);
                client = server.accept();
                System.out.println("done");
                in = new DataInputStream(client.getInputStream());
                out = new DataOutputStream(client.getOutputStream());

                objectInput = new ObjectInputStream(client.getInputStream());
                Object obj = objectInput.readObject();
                publicKey.e = (int) obj;
                obj = objectInput.readObject();
                //l = (ArrayList<Integer>)obj;
                //System.out.println(l.get(0));
                publicKey.n = (int) obj;
                stranger1 = new Stranger(publicKey);
                System.out.println(publicKey.e);
                System.out.println(publicKey.n);
                jTextArea1.append("You Have Recieved A PublicKey From The Other Guy\n");
                jTextArea1.append("The PublicKey Is:  (" + publicKey.e + "," + publicKey.n + ")\n\n");
                while (true) {

                    msg = in.readUTF();
                    System.out.println(msg);
                    jTextArea1.append("Owner: " + msg + "\n");
                }
            } catch (IOException ex) {
                Logger.getLogger(StrangerGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StrangerGui.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    server.close();
                    client.close();
                    in.close();
                    out.close();
                    objectInput.close();
                } catch (IOException ex) {
                    Logger.getLogger(StrangerGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }
    static Reading r = new Reading();

    /**
     * Creates new form StrangerGui
     */
    public StrangerGui() {
        initComponents();
        setTitle("Stranger");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            if (!jTextField1.getText().equalsIgnoreCase("")) {
                encArrayList = stranger1.getEcryptedObject(jTextField1.getText());
                ObjectOutputStream objectOutput = new ObjectOutputStream(client.getOutputStream());
                objectOutput.writeObject(encArrayList);
                encArrayList.clear();
                jTextArea1.append("You: " + jTextField1.getText() + "\n");
                jTextField1.setText("");
            }

        } catch (IOException ex) {
            Logger.getLogger(StrangerGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StrangerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StrangerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StrangerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StrangerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StrangerGui().setVisible(true);
                jTextField1.addKeyListener( // Send msg When Enter Is Pressed.
                        new KeyAdapter() {
                    public void keyReleased(KeyEvent eb) {
                        if (eb.getKeyCode() == KeyEvent.VK_ENTER) {
                            try {
                                // TODO add your handling code here:
                                if (!jTextField1.getText().equalsIgnoreCase("")) {
                                    encArrayList = stranger1.getEcryptedObject(jTextField1.getText());
                                    ObjectOutputStream objectOutput = new ObjectOutputStream(client.getOutputStream());
                                    objectOutput.writeObject(encArrayList);
                                    encArrayList.clear();
                                    jTextArea1.append("You: " + jTextField1.getText() + "\n");
                                    jTextField1.setText("");
                                }

                            } catch (IOException ex) {
                                Logger.getLogger(StrangerGui.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                }
                );
            }
        });
        r.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
